version: "3.4"

services:
  nginx:
    image: docker.io/nginxinc/nginx-unprivileged:1.23-alpine
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: .
      target: symfony_php
    depends_on:
      - db
    restart: unless-stopped
    volumes:
 #     - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      - .:/var/www/html
      - /var/www/vendor
    user: "${UID:-1000}:${GID:-1000}"
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    expose:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .container.env.local
  db:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - data-volume:/var/lib/postgresql/data/
    logging:
      driver: none
    ports:
      - 5432:5432

volumes:
  data-volume:
